### ISSUE TITLE
ask a question

### ISSUE THREAD

**Issue by Wangman1** [NcJie/DCTNet#1]
Hi, I'm a  first-year graduate student , and I'm sorry to disturb you, I want to inquiry you that can you provide the other database that used in your  paper, "DCTNet A Simple Learning-free Approach for Face Recognition", because We can not found these in anyway, thank you very much , We  just use it for my research.

**Comment by NcJie** [comment]
Hi @Wangman1, due to the dataset sharing permission agreement I cannot share the dataset here. And also the dataset are preprocessed (with eyes aligned). 

You could obtain the dataset from the original source for free 

1. FERET (subsets) 
    - https://www.nist.gov/itl/iad/image-group/color-feret-database 

2. AR
    - http://www2.ece.ohio-state.edu/~aleix/ARdatabase.html

**Comment by Wangman1** [comment]
Hello, thank you very much for your reply, I will use the url you provided to download.
